from __future__ import annotations

from datetime import date, time

from fastapi import APIRouter, Depends, HTTPException
from pydantic import BaseModel, Field
from sqlalchemy.ext.asyncio import AsyncSession

from ..database import get_db
from ..dependencies import get_current_user
from ..models import User
from ..services import compatibility_service

router = APIRouter()


class CompatibilityIn(BaseModel):
    partner_dob:         date
    partner_tob:         time
    partner_birth_place: str = Field(..., min_length=2)


class CompatibilityOut(BaseModel):
    overall_score:       float
    love_score:          float
    career_score:        float
    communication_score: float
    trust_score:         float
    summary:             str
    strengths:           list[str]
    challenges:          list[str]


@router.post(
    "",
    response_model=CompatibilityOut,
    summary="Vedic compatibility (Ashtakoot Milan) between the current user and a partner",
)
async def check_compatibility(
    body:         CompatibilityIn,
    current_user: User          = Depends(get_current_user),
    db:           AsyncSession  = Depends(get_db),
) -> CompatibilityOut:
    """
    Computes a simplified 4-factor Ashtakoot Milan score (Nadi, Gana, Bhakoot,
    Graha Maitri) and life-area scores (love, career, communication, trust).
    A narrative summary is generated by gpt-4o-mini.

    Requires the current user to have a computed birth chart.
    """
    if current_user.birth_chart is None:
        raise HTTPException(
            status_code=400,
            detail="Birth chart not found. Compute your birth chart first.",
        )

    result = await compatibility_service.check_compatibility(
        user=current_user,
        partner_dob=body.partner_dob,
        partner_tob=body.partner_tob,
        partner_birth_place=body.partner_birth_place,
        db=db,
    )
    return CompatibilityOut(**result.__dict__)
