"""initial_schema

Revision ID: b95e4cf59391
Revises: 
Create Date: 2026-05-25 18:07:39.316884

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic
revision: str = 'b95e4cf59391'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('birth_chart_cache',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('dob', sa.Date(), nullable=False),
    sa.Column('tob', sa.Time(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lng', sa.Float(), nullable=False),
    sa.Column('chart_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('hit_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_hit_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_birth_chart_cache')),
    sa.UniqueConstraint('dob', 'tob', 'lat', 'lng', name='uq_birth_chart_cache_params')
    )
    op.create_table('place_geocache',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('place_name', sa.String(length=200), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lng', sa.Float(), nullable=False),
    sa.Column('hit_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_hit_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_place_geocache'))
    )
    op.create_index(op.f('ix_place_geocache_place_name'), 'place_geocache', ['place_name'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('firebase_uid', sa.String(length=128), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('language', sa.Enum('en', 'hi', name='language_enum'), nullable=False),
    sa.Column('dob', sa.Date(), nullable=True),
    sa.Column('tob', sa.Time(), nullable=True),
    sa.Column('birth_place', sa.String(length=200), nullable=True),
    sa.Column('birth_lat', sa.Float(), nullable=True),
    sa.Column('birth_lng', sa.Float(), nullable=True),
    sa.Column('whatsapp_enabled', sa.Boolean(), nullable=False),
    sa.Column('whatsapp_delivery_time', sa.String(length=8), nullable=True),
    sa.Column('subscription_status', sa.Enum('trial', 'active', 'expired', 'cancelled', name='subscription_status_enum'), nullable=False),
    sa.Column('trial_ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('subscription_ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('razorpay_subscription_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_active_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('razorpay_subscription_id', name=op.f('uq_users_razorpay_subscription_id'))
    )
    op.create_index(op.f('ix_users_firebase_uid'), 'users', ['firebase_uid'], unique=True)
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=True)
    op.create_index(op.f('ix_users_subscription_status'), 'users', ['subscription_status'], unique=False)
    op.create_table('birth_charts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('chart_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('sun_sign', sa.String(length=20), nullable=True),
    sa.Column('moon_sign', sa.String(length=20), nullable=True),
    sa.Column('ascendant', sa.String(length=20), nullable=True),
    sa.Column('current_dasha', sa.String(length=40), nullable=True),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_birth_charts_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_birth_charts'))
    )
    op.create_index(op.f('ix_birth_charts_user_id'), 'birth_charts', ['user_id'], unique=True)
    op.create_table('chat_messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('user', 'assistant', name='message_role_enum'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('topic', sa.String(length=60), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_chat_messages_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chat_messages'))
    )
    op.create_index(op.f('ix_chat_messages_created_at'), 'chat_messages', ['created_at'], unique=False)
    op.create_index(op.f('ix_chat_messages_user_id'), 'chat_messages', ['user_id'], unique=False)
    op.create_table('daily_scores',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('score_date', sa.Date(), nullable=False),
    sa.Column('career', sa.Float(), nullable=False),
    sa.Column('love', sa.Float(), nullable=False),
    sa.Column('money', sa.Float(), nullable=False),
    sa.Column('health', sa.Float(), nullable=False),
    sa.Column('overall', sa.Float(), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_daily_scores_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_daily_scores')),
    sa.UniqueConstraint('user_id', 'score_date', name='uq_daily_score_user_date')
    )
    op.create_index(op.f('ix_daily_scores_score_date'), 'daily_scores', ['score_date'], unique=False)
    op.create_index(op.f('ix_daily_scores_user_id'), 'daily_scores', ['user_id'], unique=False)
    op.create_table('horoscopes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('period', sa.Enum('daily', 'weekly', 'monthly', name='horoscope_period_enum'), nullable=False),
    sa.Column('for_date', sa.Date(), nullable=False),
    sa.Column('language', sa.String(length=5), nullable=False),
    sa.Column('content_en', sa.Text(), nullable=True),
    sa.Column('content_hi', sa.Text(), nullable=True),
    sa.Column('whatsapp_sent', sa.Boolean(), nullable=False),
    sa.Column('whatsapp_sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_horoscopes_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_horoscopes')),
    sa.UniqueConstraint('user_id', 'period', 'for_date', name='uq_horoscope_user_period_date')
    )
    op.create_index(op.f('ix_horoscopes_for_date'), 'horoscopes', ['for_date'], unique=False)
    op.create_index(op.f('ix_horoscopes_user_id'), 'horoscopes', ['user_id'], unique=False)
    op.create_table('insight_predictions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('category', sa.Enum('career', 'love', 'money', 'health', name='insight_category_enum'), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('content_en', sa.Text(), nullable=True),
    sa.Column('content_hi', sa.Text(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('best_period_label', sa.String(length=40), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_insight_predictions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_insight_predictions')),
    sa.UniqueConstraint('user_id', 'category', 'period_start', name='uq_insight_user_category_period')
    )
    op.create_index(op.f('ix_insight_predictions_user_id'), 'insight_predictions', ['user_id'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('razorpay_payment_id', sa.String(length=64), nullable=False),
    sa.Column('razorpay_subscription_id', sa.String(length=64), nullable=True),
    sa.Column('razorpay_order_id', sa.String(length=64), nullable=True),
    sa.Column('amount_paise', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=5), nullable=False),
    sa.Column('status', sa.Enum('created', 'authorized', 'captured', 'refunded', 'failed', name='payment_status_enum'), nullable=False),
    sa.Column('webhook_event', sa.String(length=80), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_payments_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payments')),
    sa.UniqueConstraint('razorpay_payment_id', name=op.f('uq_payments_razorpay_payment_id'))
    )
    op.create_index(op.f('ix_payments_razorpay_subscription_id'), 'payments', ['razorpay_subscription_id'], unique=False)
    op.create_index(op.f('ix_payments_status'), 'payments', ['status'], unique=False)
    op.create_index(op.f('ix_payments_user_id'), 'payments', ['user_id'], unique=False)
    op.create_table('today_data',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('for_date', sa.Date(), nullable=False),
    sa.Column('panchang', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('muhurtas', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('lucky_color', sa.Text(), nullable=True),
    sa.Column('lucky_number', sa.Integer(), nullable=True),
    sa.Column('lucky_direction', sa.Text(), nullable=True),
    sa.Column('lucky_gem', sa.Text(), nullable=True),
    sa.Column('mantra_en', sa.Text(), nullable=True),
    sa.Column('mantra_hi', sa.Text(), nullable=True),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_today_data_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_today_data')),
    sa.UniqueConstraint('user_id', 'for_date', name='uq_today_data_user_date')
    )
    op.create_index(op.f('ix_today_data_for_date'), 'today_data', ['for_date'], unique=False)
    op.create_index(op.f('ix_today_data_user_id'), 'today_data', ['user_id'], unique=False)
    op.create_table('whatsapp_deliveries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('for_date', sa.Date(), nullable=False),
    sa.Column('language', sa.String(length=5), nullable=False),
    sa.Column('template_name', sa.String(length=80), nullable=False),
    sa.Column('meta_message_id', sa.String(length=120), nullable=True),
    sa.Column('status', sa.Enum('queued', 'sent', 'delivered', 'failed', name='delivery_status_enum'), nullable=False),
    sa.Column('error_message', sa.String(length=300), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_whatsapp_deliveries_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_whatsapp_deliveries')),
    sa.UniqueConstraint('meta_message_id', name=op.f('uq_whatsapp_deliveries_meta_message_id'))
    )
    op.create_index(op.f('ix_whatsapp_deliveries_status'), 'whatsapp_deliveries', ['status'], unique=False)
    op.create_index(op.f('ix_whatsapp_deliveries_user_id'), 'whatsapp_deliveries', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_whatsapp_deliveries_user_id'), table_name='whatsapp_deliveries')
    op.drop_index(op.f('ix_whatsapp_deliveries_status'), table_name='whatsapp_deliveries')
    op.drop_table('whatsapp_deliveries')
    op.drop_index(op.f('ix_today_data_user_id'), table_name='today_data')
    op.drop_index(op.f('ix_today_data_for_date'), table_name='today_data')
    op.drop_table('today_data')
    op.drop_index(op.f('ix_payments_user_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_status'), table_name='payments')
    op.drop_index(op.f('ix_payments_razorpay_subscription_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_insight_predictions_user_id'), table_name='insight_predictions')
    op.drop_table('insight_predictions')
    op.drop_index(op.f('ix_horoscopes_user_id'), table_name='horoscopes')
    op.drop_index(op.f('ix_horoscopes_for_date'), table_name='horoscopes')
    op.drop_table('horoscopes')
    op.drop_index(op.f('ix_daily_scores_user_id'), table_name='daily_scores')
    op.drop_index(op.f('ix_daily_scores_score_date'), table_name='daily_scores')
    op.drop_table('daily_scores')
    op.drop_index(op.f('ix_chat_messages_user_id'), table_name='chat_messages')
    op.drop_index(op.f('ix_chat_messages_created_at'), table_name='chat_messages')
    op.drop_table('chat_messages')
    op.drop_index(op.f('ix_birth_charts_user_id'), table_name='birth_charts')
    op.drop_table('birth_charts')
    op.drop_index(op.f('ix_users_subscription_status'), table_name='users')
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.drop_index(op.f('ix_users_firebase_uid'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_place_geocache_place_name'), table_name='place_geocache')
    op.drop_table('place_geocache')
    op.drop_table('birth_chart_cache')
    # ### end Alembic commands ###
