// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChGEQSZifhuDjHYgMP_cqqmlou48QuHxU',
    appId: '1:99204674927:web:b79ef6ca6c207cf6fd649a',
    messagingSenderId: '99204674927',
    projectId: 'astro-cd751',
    authDomain: 'astro-cd751.firebaseapp.com',
    storageBucket: 'astro-cd751.firebasestorage.app',
    measurementId: 'G-LFZRWRGN64',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhYKRrDLuONeq7t_vWyDQi_9obGHUSfr4',
    appId: '1:99204674927:android:a37f39c386d8cfa4fd649a',
    messagingSenderId: '99204674927',
    projectId: 'astro-cd751',
    storageBucket: 'astro-cd751.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAiOXQ5eQAau6ia-ZV8kS56f6t_sUwD4Lc',
    appId: '1:99204674927:ios:22ea371214c9c4b2fd649a',
    messagingSenderId: '99204674927',
    projectId: 'astro-cd751',
    storageBucket: 'astro-cd751.firebasestorage.app',
    iosBundleId: 'com.kundliai.kundliaiApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAiOXQ5eQAau6ia-ZV8kS56f6t_sUwD4Lc',
    appId: '1:99204674927:ios:22ea371214c9c4b2fd649a',
    messagingSenderId: '99204674927',
    projectId: 'astro-cd751',
    storageBucket: 'astro-cd751.firebasestorage.app',
    iosBundleId: 'com.kundliai.kundliaiApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyChGEQSZifhuDjHYgMP_cqqmlou48QuHxU',
    appId: '1:99204674927:web:54b6e86379030b6ffd649a',
    messagingSenderId: '99204674927',
    projectId: 'astro-cd751',
    authDomain: 'astro-cd751.firebaseapp.com',
    storageBucket: 'astro-cd751.firebasestorage.app',
    measurementId: 'G-KLKLYL36DB',
  );
}
